#!/usr/bin/env bash
#
#  tesserad The tessera core server.
#
#
# chkconfig: 345 80 20
# description: tesserad
# processname: tesserad
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/tesserad, see below
if [ -f /etc/sysconfig/tesserad ]; then
        . /etc/sysconfig/tesserad
fi

RETVAL=0

prog=tesserad
# you can override the lockfile via TESSERAD_LOCKFILE in /etc/sysconfig/tesserad
lockfile=${TESSERAD_LOCKFILE-/var/lock/subsys/tesserad}

# tesserad defaults to /usr/bin/tesserad, override with TESSERAD_BIN
tesserad=${TESSERAD_BIN-/usr/bin/tesserad}

# tesserad opts default to -disablewallet, override with TESSERAD_OPTS
tesserad_opts=${TESSERAD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $tesserad $tesserad_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
